namespace EducationApp.Services
{
    public interface ILocalizedStringProvider
    {
        string GetLocalizedString(Localized identifier);
        string GetLocalizedString(LanguageCode identifier);
    }

    // ReSharper disable InconsistentNaming
    public enum Localized
    {
        CoursesPivotItem_Header,
        NoCoursesFound_Text,
        SearchBox_PlaceholderText,
        SearchFaulted_Text,
        ApplicationName,
        Login_Label,
        LanguageCode,
        AuthenticationError,
        ConnectionProblem,
        Email_Text,
        FirstName_Text,
        LastName_Text,
        Loading,
        Logout_Label,
        NoInternetConnection,
        PleaseLogin_Text,
        ProfilePivotItem_Header,
        Searching,
        SomethingWrong,
        NoCoursesInCategory_Text,
        Audience_Text,
        CourseContent_Text,
        Days_Text,
        DescriptionPivotItem_Header,
        Duration_Text,
        InformationPivotItem_Header,
        InstructorEmployer_Text,
        InstructorName_Text,
        InstructorPivotItem_Header,
        Materials_Text,
        Methods_Text,
        NoInstructor_Text,
        Objectives_Text,
        OpenBrowserCourse_Content,
        Platforms_Text,
        Price_Text,
        Publisher_Text,
        SendInstructorMail_Content,
        StartDate_Text,
        TapSwitchDescription_Text,
        ClassRoom_Text,
        EndTime_Text,
        Instructor_Text,
        NoSessionsFound_Text,
        Preparation_Text,
        SchedulePivotItem_Header,
        Sessions_Label,
        StartTime_Text,
        AddParticipant_Content,
        City_Text,
        Company_Text,
        Concepts_Text,
        ContactError,
        ContactPivotItem_Header,
        Country_Text,
        Fax_Text,
        FeedbackPivotItem_Header,
        FeedbackSent,
        Global_Text,
        GoalAttained_Text,
        InDepth_Text,
        InstructorInteraction_Text,
        InstructorKnowledge_Text,
        InstructorPresentation_Text,
        JobTitle_Text,
        Message_Text,
        MessageSent,
        Number_Text,
        Organization_Text,
        Participants_Text,
        Phone_Text,
        Prerequisites_Text,
        Remarks_Text,
        RemoveParticipant_Text,
        SendFeedback_Content,
        SendMessage_Content,
        SendSubscription_Content,
        Street_Text,
        Subject_Text,
        SubscribePivotItem_Header,
        SubscriptionSent,
        Success,
        WellPaced_Text,
        WellStructured_Text,
        ZIP_Text,
        CompanyInfo,
        VAT_Text,
        en,
        fr,
        nl,
        ChangeLanguage_Label,
        FeedbackDescription_Text,
        Submitting,
        SendUsAMessage_Text,
        SubscribeDescription_Text
    }

    public enum LanguageCode
    {
        nl,
        fr,
        en
    }

    // ReSharper restore InconsistentNaming
}